### PR TITLE
Add highlight of street on mouse hover and reset when mouse off

### PR DESCRIPTION
**Pull request by leplerjacob**

### CODE REVIEW

**Comment by leplerjacob** [comment]
@CoryLR

**Comment by leplerjacob** [comment]
I realize this wasn't really a requirement of issue #90. But thought I'd try to add it anyways :)

**Comment by banjtheman** [comment]
Works great!!! The next step would be on user click the street, the street stays highlighted

**Comment by CoryLR** [comment]
@leplerjacob Love this! One improvement I may recommend is to highlight the full length of the road as currently it seems only the individual road segments are being highlighted

**Comment by leplerjacob** [comment]
@CoryLR Agreed. That was what I was trying to figure out.

**Pull request merged**
